export const REQUEST_ACTION = 'REQUEST_ACTION';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const LOG_USER_OUT = 'LOG_USER_OUT';
