export const REQUEST_ACTION = 'REQUEST_ACTION';
export const GET_SHIPMENT_SUCCESS = 'GET_SHIPMENT_SUCCESS';
export const CREATE_SHIPMENT_SUCCESS = 'CREATE_SHIPMENT_SUCCESS';
export const EDIT_SHIPMENT_SUCCESS = 'EDIT_SHIPMENT_SUCCESS';
export const DELETE_SHIPMENT_SUCCESS = 'DELETE_SHIPMENT_SUCCESS';
